// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///

namespace sandwichhero
{
public static class GPGSIds
{
        public const string achievement_10_perfect_launches = "CgkIm8DKqdILEAIQFw"; // <GPGSID>
        public const string achievement_5_perfect_launches = "CgkIm8DKqdILEAIQFg"; // <GPGSID>
        public const string achievement_make_your_first_sandwich = "CgkIm8DKqdILEAIQAg"; // <GPGSID>
        public const string achievement_stack_125_toppings_on_a_sandwich = "CgkIm8DKqdILEAIQEQ"; // <GPGSID>
        public const string achievement_make_50_sandwiches = "CgkIm8DKqdILEAIQBQ"; // <GPGSID>
        public const string achievement_make_25_sandwiches = "CgkIm8DKqdILEAIQBg"; // <GPGSID>
        public const string achievement_10_perfect_landings = "CgkIm8DKqdILEAIQHA"; // <GPGSID>
        public const string leaderboard_biggest_sandwich = "CgkIm8DKqdILEAIQFA"; // <GPGSID>
        public const string achievement_stack_150_toppings_on_a_sandwich = "CgkIm8DKqdILEAIQDw"; // <GPGSID>
        public const string achievement_25_perfect_launches = "CgkIm8DKqdILEAIQGA"; // <GPGSID>
        public const string achievement_25_perfect_landings = "CgkIm8DKqdILEAIQHQ"; // <GPGSID>
        public const string achievement_make_10_sandwiches = "CgkIm8DKqdILEAIQBA"; // <GPGSID>
        public const string achievement_perfect_launch = "CgkIm8DKqdILEAIQEg"; // <GPGSID>
        public const string achievement_stack_100_toppings_on_a_sandwich = "CgkIm8DKqdILEAIQDg"; // <GPGSID>
        public const string achievement_perfect_landing = "CgkIm8DKqdILEAIQGg"; // <GPGSID>
        public const string achievement_5_perfect_landings = "CgkIm8DKqdILEAIQGw"; // <GPGSID>
        public const string achievement_stack_175_toppings_on_a_sandwich = "CgkIm8DKqdILEAIQEA"; // <GPGSID>
        public const string achievement_stack_75_toppings_on_a_sandwich = "CgkIm8DKqdILEAIQDQ"; // <GPGSID>

}
}
